# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.1.0
      with:
        args: '*.md'

    - name: Set up Python environment
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort
        pip install black
        pip install pycodestyle
        pip install flake8
        pip install pep8-naming
        pip install yapf
    - name: isort Lint
      run: |
        isort --rr –y .
    - name: black Lint
      run: |
        black --config=.style.blackformat .
    - name: pycodestyle Lint
      run: |
        pycodestyle --config=.style.pycodestyle .
    - name: flake8 Lint
      run: |
        flake8 --config=.style.flake8 .
#    - name: yapf Lint
#      run: | 
#        yapf -i -r .
